### ISSUE TITLE
Dcmgr::Scheduler::IPAddress::Incremental#schedule bug

### ISSUE THREAD

**Issue by hansode** [axsh/wakame-vdc#475]
The following test result is unstable.

```
Failures:

  1) Dcmgr::Scheduler::IPAddress::Incremental#schedule happy paths when reaching the end of all dhcp ranges while past ip addresses have been released assigns the released ip addresses in incremental order
     Failure/Error: expect(ip_of network_vif).to eq "192.168.0.3"
       
       expected: "192.168.0.3"
            got: "192.168.0.5"
       
       (compared using ==)
     # ./spec/dcmgr/scheduler/ip_address/incremental_examples/wraparound_dhcp_range.rb:32:in `block (3 levels) in <top (required)>'
```
