### ISSUE TITLE
Load balancer spec selection

### ISSUE THREAD

**Issue by Metallion** [axsh/wakame-vdc#52]
Currently it is not possible to select a load balancer spec in the GUI. The GUI looks for a load balancer with 1000 max connections. This is hard coded and it will fail if there is no spec for 1000 connections defined in load_balancer_spec.yml

My idea is to display a selection of load balancer spec names.  Imagine the following load_balancer_spec.yml file.

```

---
lb.small:
  description: "haproxy with 1000 mac connections"
  cpu_cores: 2
  memory_size: 1024
  engine: "haproxy"
  max_connection: 1000

lb.large:
  description: "haproxy with 5000 max connections"
  engine: "haproxy"
  max_connection: 5000
```

The GUI should have a drop down list showing "lb.small" and "lb.large". When one of them is selected, the description should be shown to the user.
