### ISSUE TITLE
API: Add vdc api

### ISSUE THREAD

**Issue by t-iwano** [axsh/wakame-vdc#646]

**Comment by t-iwano** [comment]
## POST API

### reqest
``
/api/12.03/cluster
``

params 
```
cloud: string,  required # local, aws, softlayer
instance_type: string, required # docker, openstack
instance_spec: string, requried # minimal, medium, large
number: int, options # default 1
```

### response:

```
{
  :vdc_id => vdc-xxxxx,
  :cloud => softlayer,
  :instance_type => openstack,
  :instance_spec => medium,
  :number => 5,
  :state => initializing,
  :instances => [
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
  ],
  :endpoint => http://localhost:8080/,
}
```

**Comment by t-iwano** [comment]
## GET API

### request
``
/api/12.03/cluster/:vdc-id
``

### response
```
{
  :vdc_id => vdc-xxxxx,
  :cloud => softlayer,
  :instance_type => openstack,
  :instance_spec => medium,
  :number => 5,
  :state => running,
  :instances => [
    {:uuid => i-xxxxx, :state => running},
    {:uuid => i-xxxxx, :state => running},
    {:uuid => i-xxxxx, :state => running},
  ],
  :endpoint => http://localhost:8080/,
}
```

**Comment by t-iwano** [comment]
## DELETE API

### request
``
/api/12.03/cluster/:vdc-id
``

### response
```
[ vdc-id ]
```

**Comment by t-iwano** [comment]
## Database Table 

### vdc-ids
```
primary_key :id , type=>"int(11)", :null=>false,
column :uuid, "varchar(255)", :null=>false,
column :account_id, "varchar(255)", :null=>false,
column :created_at, "datetime", :null=>false,
column :updated_at, "datetime", :null=>false,
column :deleted_at, "datetime"

index [:uuid], :unique=>true, :name=>uuid
```

### clusters
```
primary_key :id , type=>"int(11)", :null=>false,
column :uuid, "varchar(255)", :null=>false,
column :vdc_id, "varchar(255)", :null=>false,"
column :account_id, "varchar(255)", :null=>false,
column :cloud, "varchar(255)", :null=>false,
column :instance_type, "varchar(255)", :null=>false,
column :cluster_spec, "varchar(255)", :null=>false,
column :created_at, "datetime", :null=>false,
column :updated_at, "datetime", :null=>false,
column :deleted_at, "datetime"

index [:uuid], :unique=>true, :name=>uuid
```

### instances 
```
column :vdc_id, "varchar(255)"
```

**Comment by t-iwano** [comment]
## yaml file
```
---
small: # cluster_spec
  docker: # instance_type
    local: # cloud
      image_id: wmi-xxxxxxxx
      hypervisor: kvm
      cpu_cores: 1
      memory_size: 256
      host_group: hng-local
    aws:
      image_id: wmi-xxxxxxxx
      hypervisor: lxc
      cpu_cores: 1
      memory_size: 256
      host_group: hng-aws
    softlayer:
       image_id: wmi-xxxxxxxx
      hypervisor: kvm
      cpu_cores: 1
      memory_size: 256
      host_group: hng-softlayer
  openstack:
medeum:
  =======
  =======
large:
  =======
  =======
```

**Comment by t-iwano** [comment]
名前の一覧を提供するapiが必要かもしれない。

**Comment by t-iwano** [comment]
requiredパラメータをちゃんと決める

vdc_id 1idでクラウドをまたぐのかどうか。
*  またぐのであればhash型になるのか？
*  1:1ならstring型

入力値はできるだけすくなく、requiredだけまず決める。

**Comment by t-iwano** [comment]
dbテーブルは以下2つでいいのではないか。

virtual_data_center
```
primary_key :id , type=>"int(11)", :null=>false,
column :uuid, "varchar(255)", :null=>false,
column :account_id, "varchar(255)", :null=>false,
column :created_at, "datetime", :null=>false,
column :updated_at, "datetime", :null=>false,
column :deleted_at, "datetime"

index [:uuid], :unique=>true, :name=>uuid
```


vdc_instances
```
primary_key :id, :type=>"int(11)"
column :vdc_id, "int(11)", :null=>false
column :instance_id, "int(11)", :null=>false
```

**Comment by t-iwano** [comment]
TODO

* docker,openstackのapi endpointは１つ
* 最少構成は全部入りで1つのインスタンス
* 構成によってはクラウドをまたいで複数台起動することもあり得る
* docker api を使用して起動するコンテナ(wakame instance)はdockerが管理すればよい
* openstackが起動したインスタンスについても同様でopenstackが管理すればよい
* openstackのimage（例えばnovaとか）を追加する場合はvdc-apiが管理する
* 構成についてはスケールアップとスケールアウトを考えなければならないが現状の制約としてインスタンスの台数のみ増やすことになる
* post apiは構成ファイルを流し込んで内容を読み取りマシンイメージを起動するようなものにする
* 構成ファイルはyaml形式にする（将来的にはjsonなども対応する必要がある)
* get apiでなにを表示するのかを考える必要がある
  * 起動しているインスタンスの情報はinstance apiで見れればよいのではないか
  * capacityを表示するべきではないか

最初はpost api実行時に必要な構成ファイルの内容を考える

**Comment by t-iwano** [comment]
インスタンスを起動するのに最低限必要なパラメータ
```
---
image_id: wmi-xxxxxxxx
hypervior: kvm
cpu_cores: 2
memory_size: 2048
ssh_key_id: ssh-xxxxxxxx
vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}
```

**Comment by t-iwano** [comment]
複数台構成の時
```
---
manager:
  image_id: wmi-xxxxxxxx
  hypervior: kvm
  cpu_cores: 2
  memory_size: 2048
  ssh_key_id: ssh-xxxxxxxx
  vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}
  host_group: hng-local
nova:
  image_id: wmi-xxxxxxxx
  hypervior: kvm
  cpu_cores: 2
  memory_size: 2048
  ssh_key_id: ssh-xxxxxxxx
  vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}
  host_group: hng-aws
key-store:
  image_id: wmi-xxxxxxxx
  hypervior: kvm
  cpu_cores: 2
  memory_size: 2048
  ssh_key_id: ssh-xxxxxxxx
  vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}
  host_group: hng-softlayer
```

**Comment by t-iwano** [comment]
```
---
vdc-spec: small # or medium or large

hypervior: kvm # or lxc
cpu_cores: 2
memory_size: 2048
ssh_key_id: ssh-xxxxxxxx
vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}
host_group: hng-local

docker:
  image_id: wmi-xxxxxxxx
  # hypervior: kvm
  # cpu_cores: 2
  # memory_size: 2048
  # ssh_key_id: ssh-xxxxxxxx
  # vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}
  # host_group: hng-local

openstack:
  manager:
    image_id: wmi-xxxxxxxx
    # hypervior: kvm
    # cpu_cores: 2
    # memory_size: 2048
    # ssh_key_id: ssh-xxxxxxxx
    # vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}
    # host_group: hng-local
  nova:
    image_id: wmi-xxxxxxxx
    # hypervior: kvm
    # cpu_cores: 2
    # memory_size: 2048
    # ssh_key_id: ssh-xxxxxxxx
    # vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}
    # host_group: hng-local
  swift:
    image_id: wmi-xxxxxxxx
    # hypervior: kvm
    # cpu_cores: 2
    # memory_size: 2048
    # ssh_key_id: ssh-xxxxxxxx
    # vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}
    # host_group: hng-local
```

**Comment by t-iwano** [comment]
* vdc-specはyamlファイルではなくrequiredのパラメータにしたほうがよいかもしれない。
* cpu_cores, memory_size, imageのdisk_sizeについて
  * 案1: api側でvalidationをかける
  * 案2: vdc-specのパラメータによって決まるのでcpu_cores, memory_sizeはここでは書かない
* vdc-specごとに使用できるimage fileの一覧を取得できるapiが必要かもしれない

**Comment by t-iwano** [comment]
```
---
instance_spec:
  tiny_local:
    cpu_cores: 2
    memory_size: 2048
    host_group: hng-xxxxx
    hypervisor: kvm
  tiny_aws:
  tiny_softlayer:

networks:
  nw-pub:
  nw-pri:

vdc-spec:
  docker_api:
    instance_spec: tiny_local
    image_id: wmi-xxxx
    user-data: {}
    ssh-key: ssh-xxxxx
    vifs: {}
  docker_continer:
```

**Comment by t-iwano** [comment]
Dropbox (Axsh)\axsh\integration\2015\20150519-SI-TIS(Virtual Data Centerの開発)\90_資料\20150623_Kick-off

**Comment by t-iwano** [comment]
## POST API

### request
```
/api/12.03/virtual_data_center
```

#### params
```
type: string, required # docker or openstack
spec: string or file, required 
```

### response
```
{
  :uuid => vdc-xxxx,
  :vdc_specs => {}
  :instances => [
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
  ],
  :endpoint => http://localhost:8080/,
}
```

**Comment by t-iwano** [comment]
## DELETE API

### request
```
/api/12.03/virtual_data_center/:vdc_id
```

### response
```
[ vdc_id ]
```

**Comment by t-iwano** [comment]
## GET API

### request
```
/api/12.03/virtual_data_center/:vdc_id
```

### response
```
{
  :uuid => vdc-xxxx,
  :vdc_specs => {}
  :instances => [
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
  ],
  :endpoint => http://localhost:8080/,
}
```

**Comment by Metallion** [comment]
一番上に細かくfeatureの説明書いてくれない？このAPIで何をすると言う説明。

**Comment by t-iwano** [comment]
ok

**Comment by t-iwano** [comment]
TODO:
capacityの表示の仕方を考える。

**Comment by t-iwano** [comment]
virtual_data_center
```
primary_key :id , type=>"int(11)", :null=>false,
column :uuid, "varchar(255)", :null=>false,
column :account_id, "varchar(255)", :null=>false,
column :created_at, "datetime", :null=>false,
column :updated_at, "datetime", :null=>false,
column :deleted_at, "datetime"

index [:uuid], :unique=>true, :name=>uuid
```

virtual_data_center_spec
```
primary_key :id,  type=>"int(11)", :null=>false,
column :vdc_id, "int(11)", :null=>false,
column :specs, "text", :null=>false,
column :created_at, "datetime", :null=>false,
column :updated_at, "datetime", :null=>false,
column :deleted_at, "datetime"
```

vdc_instances
```
primary_key :id, :type=>"int(11)"
column :vdc_id, "int(11)", :null=>false
column :instance_id, "int(11)", :null=>false
column :created_at, "datetime", :null=>false,
column :updated_at, "datetime", :null=>false,
column :deleted_at, "datetime"
```

**Comment by akry** [comment]
spec file内のnetwork項目は不必要

**Comment by t-iwano** [comment]
TODO: 以下の項目を説明するための材料をまとめておく。

* どんなＡＰＩを作っているのか
* どんなFormatを読み込もうとしているのか
* 将来像と現状の実装について
* このissueの整理

**Comment by t-iwano** [comment]
# vdc-api

このAPIはWakame-vdc上でdockerとopenstackのクラスターを作成するAPIである。
クラスターごとにvdc-apiを付与し複数のクラスターを管理する。

## 概要

 - 作成中のAPI
	 - POST: virtual_data_center
	 - GET: virtual_data_center
	 - GET: virtual_data_center/:vdc-id
	 - DELETE: virtual_data_center/:vdc-id
 - 将来像と現状の実装について
 
## 作成中のAPI

### POST: virtual_data_center

typeとspecを指定しwakame-vdc側に登録されているクラスターを作成するAPI。
optionとして作成クラスターのspec_fileを指定することもできる。

request
```
/api/12.03/virtual_data_center
```

params
```
type: string, required # docker or openstack
spec: string, required # small or medium or large
spec_file: file_name, optional
```

spec_fileのformat
```
---
instance-spec:
  tiny_local:
    cpu_cores: 2
    memory_size: 2048
    host_group: hng-xxxxx
    hypervisor: kvm
    quota_weight: 1.0
  tiny_aws:
    cpu_cores: 2
    memory_size: 2048
    host_group: hng-xxxxx
    hypervisor: lxc
    quota_weight: 2.0
  tiny_softlayer:
    cpu_cores: 2
    memory_size: 2048
    host_group: hng-xxxxx
    hypervisor: kvm
    quota_weight: 3.0

vdc-spec:
  docker_api:
    type: docker
    spec: tiny_local
    image_id: wmi-xxxx
    user-data: {}
    ssh-key: ssh-xxxxx
    vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}

  docker_continer:
    type: docker
    spec: tiny_local
    image_id: wmi-xxxx
    user-data: {}
    ssh-key: ssh-xxxxx
    vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}
    after:
       - docker_api

  manager:
    type: openstack
    spec: tiny_local
    image_id: wmi-xxxx
    user-data: {}
    ssh-key: ssh-xxxxx
    vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}

  nova:
    type: openstack
    spec: tiny_softlayer
    image_id: wmi-xxxx
    user-data: {}
    ssh-key: ssh-xxxxx
    vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}
```

response
```
{
  :uuid => vdc-xxxx,
  :vdc_specs => {}
  :instances => [
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
  ],
  :endpoint => http://localhost:8080/,
}
```

### GET: virtual_data_center

作成したクラスターのリスト情報を取得するAPI

request
```
/api/12.03/virtual_data_center
```

response
```
[{
  :uuid => vdc-xxxx,
  :vdc_specs => {}
  :instances => [
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
  ],
  :endpoint => http://localhost:8080/,
},
{
  :uuid => vdc-xxxx,
  :vdc_specs => {}
  :instances => [
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
  ],
  :endpoint => http://localhost:8080/,
}]
```

### GET: virtual_data_center/:vdc-id

vdc-idを指定して現在のクラスターの情報を取得するAPI。

request
```
/api/12.03/virtual_data_center/:vdc_id
```

response
```
{
  :uuid => vdc-xxxx,
  :vdc_specs => {}
  :instances => [
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
    {:uuid => i-xxxxx, :state => initializing},
  ],
  :endpoint => http://localhost:8080/,
}
```

### DELETE: virtual_data_center/:vdc-id

vdc-idを指定して現在のクラスターを削除するAPI

request
```
/api/12.03/virtual_data_center/:vdc_id
```

response
```
[ vdc_id ]
```

## 将来像と現状の実装について

 - 将来的にvdc-idとinstance-idを使用してユニークなidを作ることによりinstance-idが重複しても動作できるようにしたい。
	 - 現状の実装ではinstance-idがユニークなもので動いているため重複できない。
 - クラスター作成時にspec_fileを指定しなくても動作するようにしたい。
	 - 現状ではwakame-vdc側にspec_fileを読み込ませる機能がないのでspec_fileが必須になっている。
 - 現在使用できるspecの種類を取得できるAPIがほしい。
 - POST、GETAPIにcapacityが表示されていないので現在どれだけ使用しているのかを表示できる機能を追加する必要がある。
 - 現在のクラスターのステータスが表示されていないので取得できるような機能を追加する必要がある。
 - Error処理が不十分なので追加する必要がある。
 - 現在のクラスターの構成を変更できるＡＰＩがないので構成を変更できる機能を追加する必要がある。
