### ISSUE TITLE
create virtual data center api

### ISSUE THREAD

**Issue by t-iwano** [axsh/wakame-vdc#711]
## overview
see https://github.com/axsh/wakame-vdc/issues/646#issuecomment-125430221

**Comment by Metallion** [comment]
New vdc_spec file format

filename: docker.yml

```
vdc_name: docker

---
instance_spec:
  tiny_local:
    cpu_cores: 2
    memory_size: 2048
    host_group: hng-xxxxx
    hypervisor: kvm

vdc-spec:
  docker_api:
    instance_spec: tiny_local
    image_id: wmi-xxxx
    user-data: {}
    ssh-key: ssh-xxxxx
    vifs: {"eth0":{"index":"0", "network":"nw-xxxxxxxx", "security_groups:"sg-xxxxxxxx"}}
```

**Comment by Metallion** [comment]
Spec files to create:

* web_service.spec

```
+-----------------+             +------------------+
|                 |             |                  |
|   Web server    |             |                  |
|                 +-------------+                  |
|                 |             |                  |
+-----------------+             |                  |
                                |   Load balancer  |
                                |                  |
+-----------------+             |                  |
|                 |             |                  |
|   Web server    +-------------+                  |
|                 |             |                  |
|                 |             |                  |
+-----------------+             +------------------+

```

* OpenStack.yml

An OpenStack cluster.

**Comment by t-iwano** [comment]
今のspec_file.yaml

```
---
instance_spec:
  small:
    cpu_cores: 1
    memory_size: 512
    host_node_group: hng-kvm
    hypervisor: kvm
    quota_weight: 1.0
  medium:
    cpu_cores: 1
    memory_size: 512
    host_node_group: hng-kvm
    hypervisor: kvm
    quota_weight: 1.0

vdc_spec:
  docker_api:
    instance_type: docker
    instance_spec: small
    image_id: wmi-centos63stdkvm
    ssh_key_id: ssh-dkprt2me
    vifs:
      eth0:
        index: 0
        network: nw-public
        security_groups: sg-86zj15o4
    user_data:
      port: 8080

  docker_api2:
    instance_type: docker
    instance_spec: small
    image_id: wmi-centos63stdkvm
    ssh_key_id: ssh-dkprt2me
    vifs:
      eth0:
        index: 0
        network: nw-public
        security_groups: sg-86zj15o4
```

**Comment by t-iwano** [comment]
## vdc_specの改修について

* vdc_specはいくつも登録できる。
* vdc_specに記述するvdc_nameはvdc_specの名前
* clusterを起動する時にvdc_specを起動するとvdc_specに記述されているインスタンスがすべて起動する。
  * 起動順番は最初は記述されている順番
  * 将来的にはインスタンス間のdependencyを見て起動順番を変更できるようにする。

* clusterを起動する時に必要なパラメータはvdc_nameだけ？　オプションとしてスペックファイルをそのまま渡すこともできる。
* vdc_specの登録やリスト化するapiがないので新規に作る。
* 保存するファイルの場所を決める。
* 保存するファイル名はvdc_name.ymlで決める。

**Comment by t-iwano** [comment]
```
---
vdc_name: docker

instance_spec:
  small:
    cpu_cores: 1
    memory_size: 256
    host_node_group: hng-kvm
    hypervisor: kvm
    quota_weight: 1.0

vdc_spec:
  docker_api:
    instance_spec: small
    image_id: wmi-ubuntu14043ple
    ssh_key_id: ssh-vlhfqsd3
    vifs:
      eth0:
        index: 0
        network: nw-public
        security_groups: sg-qw8o9403
```

**Comment by t-iwano** [comment]
```
vdc_name: docker

instance_spec:
  small:
    cpu_cores: 1
    memory_size: 256
    host_node_group: hng-kvm
    hypervisor: kvm
    quota_weight: 1.0

vdc_spec:
  docker_api:
    instance_spec: small
    image_id: wmi-ubuntu14043ple

ssh_key_id: ssh-vlhfqsd3
vifs:
    eth0:
      index: 0
      network: nw-public
      security_groups: sg-qw8o9403
```
